### ISSUE TITLE
Retrieving with a Filter in ReadMe is wrong

### ISSUE THREAD

**Issue by timsim00** [ExactTarget/Fuel-Node-SOAP#52]
retrieve( type, props, filter, callback )
type - object type. see object types required
props - object properties to be returned required
filter - filter object

Should be:

filter - { filter: {leftOperand...} }

Because actual code in fuel-soap.js is

186: filter = options.filter;

**Comment by vernak2539** [comment]
If could send a PR with the correct wording, that would be great.

**Comment by timsim00** [comment]
var options = {
		Name: "SDKDataExtension"	//required
		,props: ['Key', 'Value'] 	//required
		,filter: {						
        	leftOperand: 'Value',
        	operator: 'equals',
        	rightOperand: 'Some random text for the value field'
   		}
	};



DataExtensionRow.prototype.get = function(cb) {

	this.props = this.config.props || {};
	var filter = {filter: this.config.filter} || null;  <----- ********The filter object has to be wrapped in an object.********
	
	if (!this.props || helpers.isEmpty(this.props)) {
		cb({error: 'A property list is required for DE Row retrieval.', documentation: 'https://code.exacttarget.com/apis-sdks/fuel-sdks/data-extensions/data-extension-retrieve.html'});
	} else {
		this.parent.SoapClient.retrieve(
			this.objName + '[' + this.config.Name + ']',
			this.props,
			filter,   <--- ******** An object with a filter property, which is also an object. ********
			function( err, response ) {
				if ( err ) {
					cb( err );
				}
				cb(response);
			}
		);
	}		
};

**Comment by vernak2539** [comment]
@timsim00 please checkout the referenced PR. I believe this is what you were going for?
