### ISSUE TITLE
Exactly how do I add a subscriber to a list?

### ISSUE THREAD

**Issue by gscott** [ExactTarget/Fuel-Node-SOAP#54]
I'm getting super confused on how to set up the call to `soapClient.create().`

Do I set up options like this:

````
options = [{
    Name: 'SubscriberKey',
    Value: subscriberKey
  }, {
    Name: 'EmailAddress',
    Value: emailAddress
  }, {
    Name:  'ListID',
    Value: listID
  }];
````
then call the `create()` method as so? (Our subscriberKeys are emailAddresses btw).
````
soapClient.create( 'Subscriber', options, function( err, response )
````
When I do this I get `    TypeError: Uncaught error: Cannot read property 'toString' of undefined` somewhere deep in xml2js.  

Any pointers?

**Comment by vernak2539** [comment]
@gscott per the README, it seems that you're missing an argument for that function, and I assume this is why xml2js is failing.

> create | update | delete( type, props, options, callback )

**Comment by timsim00** [comment]
You'll need to pass something like this:

		var props = {"EmailAddress" : "example@bh.exacttarget.com"
				,"SubscriberKey" : "SDKSubscriber"
				,"Attributes": [{'Name': 'First Name', 'Value': 'ExactTarget Example'}]
                                ,"Lists": [{'ID':'6286','Status':'Active'}]
		}

	myClient.SoapClient.create(
		'Subscriber',
		props,
		this.options,
		function( err, response ) {
			if ( err ) {
				cb( err );
			}
			cb(response);
		}
	);

**Comment by gscott** [comment]
That is so helpful, I'll try it, thank you!

**Comment by vernak2539** [comment]
closing, as it should be solved

**Comment by gscott** [comment]
Thanks. It is resolved. It would be cool to put a few more JS examples in the README or in the ExactTarget API docs; I don't think anything explains that Attributes and Lists are to be set up intuitively like that in the properties.

**Comment by vernak2539** [comment]
@gscott yep, they are definitely lacking. I'll be transitioning the README to link to gist examples.

Once I do, it would be great to have a few PRs adding links with examples. Should have it done soon

**Comment by vernak2539** [comment]
@gscott the readme has been updated with externalized examples. Feel free to submit a PR with links to more examples! Thanks!
