### ISSUE TITLE
Custom header

### ISSUE THREAD

**Issue by timsim00** [ExactTarget/Fuel-Node-SOAP#56]
I need to create a pull request to allow for custom headers so we can track usage of the new node SDK.  Alex, do you have a preference for how that comes through?  I can add another parameter after the callback.  Or I could add it to the 'options' parameter and remove it from the options object after I process it.  Thoughts?

**Comment by vernak2539** [comment]
I would take a look at how the REST client does it. I assume you're talking about object-wide headers, not request based headers? Both a possible, but based on [this PR][3] it looks like you're going for request based headers.

**Rest Client Examples** ([object-wide headers][1]) ([request specific headers][2])

A simple lodash merge would accomplish what you want.

[1]: https://github.com/ExactTarget/Fuel-Node-REST/blob/master/lib/fuel-rest.js#L54
[2]: https://github.com/ExactTarget/Fuel-Node-REST/blob/master/lib/fuel-rest.js#L97
[3]: https://github.com/ExactTarget/Fuel-Node-SOAP/pull/57
